name: build

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

env:
  REGISTRY: localhost:5001

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build on platform
        run: |
          gh workflow run build-app.yaml \
            -R pr3s3nt/idp-platform \
            -f app_repo=${{ github.repository }} \
            -f sha=${{ github.sha }} \
            -f ref=${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
